# It contains all the configs required in the project

artifacts:
  PREPARED: prepared
  TRAIN_DATA: train.tpv
  TEST_DATA: test.tpv
  FEATURIZED_DATA: features
  FEATURIZED_DATA_TRAIN: train.pkl
  FEATURIZED_DATA_TEST: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl

metrics:
  SCORES: scores.json

plots:
  PRC: prc.json
  ROC: roc.json

source_data:
  URL: https://github.com/c17hawke/FSDS-DVC-NLP-Project-with-docs/raw/be1801e2ca505f7386860735b6b57c8abce90e60/data/data.xml
  data_dir: data
  data_file: data.xml

